import emails
from emails.template import JinjaTemplate as T

import config

email_subject = "Frosty predicts {{temperature}}° F at {{time}}"
email_contents = "<img src='temps_plot.png'><p>This message was generated by Frosty on the Raspberry Pi.</p>"


def send_email(min_data):
    '''Send an email notification
    '''

    message = emails.html(subject=T(email_subject),
                          html=T(email_contents),
                          mail_from=(config.email["from"]["name"], config.email["from"]["email"]))

    message.attach(filename='temps_plot.png',
                   data=open('temps_plot.png', 'rb'))
    message.attachments['temps_plot.png'].is_inline = True
    message.transformer.synchronize_inline_images()
    message.transformer.save()

    message.send(to=(config.email["to"]["name"], config.email["to"]["email"]),
                 render={"temperature": min_data[0], "time": min_data[1].strftime(
                     "%-I:%M %p on %A %b %-d")},
                 smtp=config.email["smtp"])
