import emails
from emails.template import JinjaTemplate as T

import config

email_subject = "Frosty predicts {{temperature}}° at {{time}}"
email_contents = "<p>This message was generated by Frosty on the Raspberry Pi.</p>"


def send_email(min_data):
    '''Send an email notification
    '''

    message = emails.html(subject=T(email_subject),
                          html=T(email_contents),
                          mail_from=(config.email["from"]["name"], config.email["from"]["email"]))

    message.send(to=(config.email["to"]["name"], config.email["to"]["email"]),
                 render={"temperature": min_data[0], "time": min_data[1]},
                 smtp=config.email["smtp"])
